name: test
on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - "**"
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Type Check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build Test
        run: npm run build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
