name: test
on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - "**"
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 22 ]
    name: Test(Node ${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Type Check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build Test
        run: npm run build
